### ISSUE TITLE
wheel >=0.32.0 breaks devpi-builder

### ISSUE THREAD

**Issue by jmaroeder** [blue-yonder/devpi-builder#107]
See this issue in `wheel`:
https://github.com/pypa/wheel/issues/255

**Comment by theMarix** [comment]
Thanks for reporting this. I haven't had time to look into recent wheel versions yet.

**Comment by theMarix** [comment]
Having taken a first look at this, the fix for this sadly won't be as trivial as adjusting a few imports. A lot of, as far as I remember back then documented, API functionality to query metadata of wheel files was removed completely and I'll have to figure out how to replace it.

**Comment by kgk** [comment]
What, if any, is the current workaround .. downgrade wheel?

**Comment by theMarix** [comment]
Yes. As an intermediate step I'll likely make a release that puts an upper limit on the wheel version. That is not a satisfying solution, though.
