### ISSUE TITLE
HTTP Auth does not work

### ISSUE THREAD

**Issue by aadis** [blue-yonder/devpi-builder#94]
We protect our devpi server with HTTP Auth. When trying to use devpi-builder to build and upload packages run into the following issue:
```
$ devpi-builder dev-requirements.txt 'https://foo:bar@pypi.example.com/user/prod/+simple/' 'user' pass 
Traceback (most recent call last):
  File "/home/aaditya/.virtualenvs/c/bin/devpi-builder", line 11, in <module>
    sys.exit(main())
  File "/home/aaditya/.virtualenvs/c/local/lib/python2.7/site-packages/devpi_builder/cli.py", line 106, in main
    with wheeler.Builder() as builder, DevpiClient(args.index, args.user, args.password) as devpi_client:
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/home/aaditya/.virtualenvs/c/local/lib/python2.7/site-packages/devpi_plumber/client.py", line 33, in DevpiClient
    wrapper.login(user, password)
  File "/home/aaditya/.virtualenvs/c/local/lib/python2.7/site-packages/devpi_plumber/client.py", line 71, in login
    return self._execute('login', user, '--password', password)
  File "/home/aaditya/.virtualenvs/c/local/lib/python2.7/site-packages/devpi_plumber/client.py", line 62, in _execute
    raise DevpiClientError(output.getvalue())
devpi_plumber.client.DevpiClientError: WARN: devpi-client-2.5.0 got an unversioned reply, assuming API-VERSION 2 (as implemented by devpi-server-2.0)
POST http://pypi.example.com/+login
401 Unauthorized: <html>
<head><title>401 Authorization Required</title></head>
<body bgcolor="white">
<center><h1>401 Authorization Required</h1></center>
<hr><center>nginx/1.2.1</center>
</body>
</html>
```

The other issue about using devpi login would solve this I believe.

**Comment by theMarix** [comment]
Devpi-builder does internally use `devpi login`. As you can see from the stack trace it is actually the command that fails. Thus, I don't see how the other issue would did this.

Does HTTP authentication require any special arguments to be passed to `devpi login`?

**Comment by aadis** [comment]
I think the problem is somewhere the URL is being parsed, reconstructed and then passed to devpi use, and the inline username:password is stripped out.

The exact same url works with devpi use though.

**Comment by aadis** [comment]
Looking around I *guess* https://github.com/blue-yonder/devpi-plumber/blob/master/devpi_plumber/client.py#L46 is the place the username:password from the url are lost.

**Comment by theMarix** [comment]
I think you are right. Feel free to create a PR. Otherwise I'll give it a shot in my next 20% time.

**Comment by aadis** [comment]
I'll try, but not promises :)

**Comment by theMarix** [comment]
I just created a small test to verify the hypothesis about `_extract_server_url` being the issue. This does not seem to be the case, though. https://travis-ci.org/theMarix/devpi-plumber/builds/124422744

**Comment by theMarix** [comment]
I actually debugged through the code and all URLs seem to be passed to the Devpi client correctly. @aadis, could you please post a `pip freeze` of a minimal virtualenv in which this issue occurs?

**Comment by theMarix** [comment]
I just managed to reproduce the issue. It is still very unclear to me what's the root cause, though.

**Comment by theMarix** [comment]
I can actually reproduce the issue with devpi client itself. If I do `devpi use https://foo:bar@pypi.example.com/user/prod` that causes the same issue, while a  `devpi use https://foo:bar@pypi.example.com` followed by  `devpi use /user/prod` works as expected.

**Comment by StephanErb** [comment]
Is it related to this one here? https://bitbucket.org/hpk42/devpi/commits/8906ec7a7459

**Comment by theMarix** [comment]
Most probably.

**Comment by theMarix** [comment]
It works for me with devpi-client 2.6.2 and the HTTP auth user matching the devpi user. If the users don't match I get a permission error on upload which I can also reproduce using the pure devpi client, so this does not seem to be a devpi-builder issue.
