### ISSUE TITLE
Add support for client certs

### ISSUE THREAD

**Issue by hlawrenz** [blue-yonder/devpi-builder#96]
We use a devpi server which requires a client certificate to connect. I'd like to add support for using client certs to devpi-builder. I submitted pull requests in both devpi-builder and devpi-plumber to add support for this a while back. Please note the failing build on the patch here is just due to lack of support in plumber. Let me know what I can do to help get those patches included.

Pull request is #69

**Comment by theMarix** [comment]
Thanks for the reminder. I wanted to check out if I can come up with an easy way to test this and then it somehow fell of my TODO list. I'll try to merge it till the end of the week.

**Comment by hlawrenz** [comment]
Excellent, thanks. As requested I rebased the pull request on plumber. All tests other than the coverage passed. I'll spend a bit of time tomorrow looking at what it'll take to write a test but from what I remember it seemed like it would be very involved.

**Comment by theMarix** [comment]
I have integrated your fix in devpi-plumber. Please recheck.

**Comment by hlawrenz** [comment]
Works perfectly. Thanks for your help with all of this!

**Comment by theMarix** [comment]
Thanks for the contribution. I have just pushed release 2.1.0, so the feature should shortly become available on PyPI.
