### ISSUE TITLE
Improve error output

### ISSUE THREAD

**Issue by cb109** [blue-yonder/devpi-builder#98]
I tried using this tool to dump a virtualenv's content and upload it to our companies devpi. It started building one package and then quit, no errors or any debug output. This is probably due to me being on Windows which cannot build some of the wheels because it is missing a compiler.

It would be great to at least get some sort of error output, similar to what we can see when dumping wheels manually using `pip wheel -r requirements.txt --wheel-dir=.wheelhouse`. This will tell me which wheel failed, so I can skip it for the moment.

Can that information be caught and piped to the console?

**Comment by theMarix** [comment]
Which version of devpi-builder did you use? Version 2.2.0 should properly include the build errors in the output. In addition, devpi-builder should continue with the next package if it fails to build one. It aborting would indicate some bug. Could you please check you are using version 2.2.0 and post the output of a minimal example?

**Comment by cb109** [comment]
I cant check right now, but it was the latest from pip. Will check next week and try again if it was an earlier version, thanks!

**Comment by cb109** [comment]
Hey, sorry for being late :smile: The version was indeed *2.2* and when I tried again, it behaved like you described (telling me which wheels failed and skipping them without interrupting the overall build). Not sure what I did on the first try to make it fail :confused: 

I'll close since I can't reproduce it anymore.

Cheers

**Comment by theMarix** [comment]
Thanks for following up!
